"""
FastAPI application for Virtual Twin Database System

Provides REST API endpoints for:
- Database management
- Simulation execution
- Experiment tracking
- Pattern discovery
- SQL queries
"""

from fastapi import FastAPI
from contextlib import asynccontextmanager
from typing import AsyncGenerator

from database.manager import TwinDatabaseManager


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator:
    """
    Manage application lifecycle
    
    Startup:
    - Initialize database tables
    - Sync configurations from manifests
    - Store manager in app state
    
    Shutdown:
    - Clean up resources
    """
    # Startup
    print("🚀 Starting Virtual Twin Database API...")
    
    # Initialize database manager
    manager = TwinDatabaseManager()
    
    # Create tables if they don't exist
    manager.create_all_tables()
    print("✓ Database tables initialized")
    
    # Sync configurations from YAML manifests
    try:
        manager.sync_configurations_from_manifests()
        print("✓ Configurations synced from manifests")
    except Exception as e:
        print(f"⚠ Warning: Could not sync manifests: {e}")
    
    # Store manager in app state for access in endpoints
    app.state.db_manager = manager
    
    print(f"✓ Ontology version: {manager.get_ontology_version()}")
    print(f"✓ Manifest version: {manager.get_manifest_version()}")
    print("✓ API ready at http://localhost:8000")
    
    yield
    
    # Shutdown
    print("\n👋 Shutting down Virtual Twin Database API...")
    # Clean up resources if needed
    

# Create FastAPI application
app = FastAPI(
    title="Virtual Twin Database API",
    description="""
    Ontology-driven virtual twin system with comprehensive data management.
    
    ## Features
    
    * **Ontology-Driven**: Structure defined in YAML, not database
    * **Simulation Management**: Run and track SimPy simulations
    * **Experiment Tracking**: Design and execute experiments
    * **Pattern Discovery**: Discover patterns from simulation data
    * **SQL Queries**: Direct SQL access to all data
    * **Repository Pattern**: Clean data access layer
    
    ## Data Sources
    
    * Historical MES data (imported from CSV)
    * Simulation results (generated by twin model)
    * Discovered patterns (from experiments)
    * Configuration from YAML manifests
    """,
    version="4.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc"
)


# Root endpoint
@app.get("/")
async def root():
    """API root endpoint with system information"""
    return {
        "message": "Virtual Twin Database API",
        "version": "4.0.0",
        "endpoints": {
            "documentation": "/docs",
            "alternative_docs": "/redoc",
            "database": "/database",
            "simulations": "/simulations", 
            "experiments": "/experiments",
            "patterns": "/patterns",
            "recommendations": "/recommendations",
            "query": "/query"
        },
        "status": "operational"
    }


# Health check endpoint
@app.get("/health")
async def health_check():
    """Health check endpoint for monitoring"""
    try:
        # Check if database is accessible
        manager = app.state.db_manager
        ontology_version = manager.get_ontology_version()
        
        return {
            "status": "healthy",
            "database": "connected",
            "ontology_version": ontology_version
        }
    except Exception as e:
        return {
            "status": "unhealthy",
            "error": str(e)
        }


# Import and include routers
from database.routers import query, simulation, experiment, database

app.include_router(query.router, prefix="/query", tags=["SQL Queries"])
app.include_router(simulation.router, prefix="/simulations", tags=["Simulations"])
app.include_router(experiment.router, prefix="/experiments", tags=["Experiments"])
app.include_router(database.router, prefix="/database", tags=["Database Management"])